name: Check Website Availability

on:
  schedule:
    - cron: '*/2 * * * *' # Runs every 30 minutes
  workflow_dispatch:      # Allows manual triggering

jobs:
  check-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check Website Status
        run: |
          STATUS=$(curl -s -o /dev/null -w '%{http_code}' https://portal.minv.sk)
          if [ "$STATUS" != "200" ]; then
            echo "Website is down! Status code: $STATUS"
            exit 1
          else
            echo "Website is up! Status code: $STATUS"
          fi
